---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: install apache2
    apt:
      name: "{{myapache}}"
      state: present

  - name: install git 
    apt:
      name: "{{mygit}}"
      state: present
    when: ansible_os_family =="Debian"  
      
  - name: install tree
    apt:
      name: "{{mytree}}"    
      state: present
    when: ansible_os_family !="Debian"

  - name: command
    command: hostname -f
    register: myresult   

  - name: debug
    debug:
      msg: "{{myresult}}" 


